### ISSUE TITLE
Translation: <language>

### ISSUE THREAD

**Issue by KingHad** [Rookiestyle/PasswordChangeAssistant#11]
![KeePass_Mn8Kp06Dec](https://user-images.githubusercontent.com/90212204/132249371-317818a2-7b8b-4883-97cc-4501e2a262df.png)
Hi

When i start Keepass, i see every time the Window with the messege: Error parsing translation file 
Fehler im XML-Dokument (8,2).

Thank you for help.

**Comment by Rookiestyle** [comment]
Which translation file and which version? I assume PasswordChangeAssistant.de.language.xml based on your screenshot?

Please retry the newest file from here and restart KeePass: https://github.com/Rookiestyle/PasswordChangeAssistant/tree/master/Translations

If the error persist, please let me know the filename.

**Comment by KingHad** [comment]
Hi 
The Translation File is "PasswordChangeAssistant.de.language" - German. Updatet 16 days ago. (MD5 Hash: 53fefd2e15ae142ff0867c476cb77822)

KeePass, i aso updatet today to version: 2.49 (64 Bit)

Password Change Assistant has the Version 2.12

The Error is still there, every start.

**Comment by Rookiestyle** [comment]
Please attach the file you use to this ticket.

Also please try the attached plugin version. It is a debug build which hopefully will show a more detailled error message. 
Let me know the error message.
[PasswordChangeAssistant.zip](https://github.com/Rookiestyle/PasswordChangeAssistant/files/7147734/PasswordChangeAssistant.zip)

**Comment by Rookiestyle** [comment]
The attached file is 183KB large and seems to be a website. I can reproduce your issue if I rename it to .xml
The file is no valid xml file and it is not the file PasswordChangeAssistant.de.language.xml from this repository.

Did you perhaps save the browser page after clicking on the german translation file?

When clicking the filename here, you have to click "Raw" to see only the file content without any github stuff.
Please try https://raw.githubusercontent.com/Rookiestyle/PasswordChangeAssistant/master/Translations/PasswordChangeAssistant.de.language.xml and save this file

**Comment by KingHad** [comment]
Hi
Yes you found the failer. I saved the file with the right-click. 
I tryed the Raw-file and it works!

it seems to be a user-failer... :/ (me)

thank you a lot for your support
bb

**Comment by Rookiestyle** [comment]
Good to know you managed to solve it
