### ISSUE TITLE
How to save own autotype setting

### ISSUE THREAD

**Issue by MikaWood** [Rookiestyle/PasswordChangeAssistant#17]
## Summary
How can i save my own autotype configuration?
i have a powershell script that needs 
           Username - CR - wait XXX
           OldPassword -CR -wait XXX
           NewPassword -CR 

i want to save the config as default

best regards
MikaWood

**Comment by Rookiestyle** [comment]
This is described in the wiki: [![Standalone form](images/PasswordChangeAssistant%20-%20standalone%20form.png)](https://github.com/Rookiestyle/PasswordChangeAssistant/wiki/Changing-passwords)

You have to input the to be used sequence as *Password Change Sequence* and change the password.
The plugin will then save this seuence for the respective entry.
