### ISSUE TITLE
In large screen scale (300%) the top botons are not displayed.

### ISSUE THREAD

**Issue by jldevv** [Rookiestyle/PasswordChangeAssistant#23]
## Steps to Reproduce
1. Open Windows configuration. 
2. Go to System -> Screen. 
3. Set scale to 300%
4. Open PasswordChangeAssistant.

## Expected Behavior
The buttons "Edit", "Auto-Type", "Change Password" and "Cancel" should been visible.
![PasswordChangeAssistant2](https://user-images.githubusercontent.com/69424909/224556310-24fd7080-89bf-442d-a07e-33fca3196545.png)

## Actual Behavior
The window is cut before the buttons.
![PasswordChangeAssistant](https://user-images.githubusercontent.com/69424909/224556341-0cbce7e3-0ca1-4c27-9c5d-32e5deef7808.png)

## Context
OS: Windows 11
KeePass Version: 2.53.1 (64-bit)
Plugin Version: v2.16

**Comment by Rookiestyle** [comment]
I can't reproduce that.

Scale was set to 250% on my latop.
I manually changed it to 300% and 350% - using the sliders as well as setting this as manual scale
The windows was completely visible all the time.

Do you face this issue right after opening the window or do you perform any action before that?
Which screen resolution do you use? My screen is set to 3840 x 2160

**Comment by Rookiestyle** [comment]
Closed due to inactivity.
