### ISSUE TITLE
The original 'Generate password' doesn't work with this plugin

### ISSUE THREAD

**Issue by lavinger** [Rookiestyle/PasswordChangeAssistant#25]
The plugin integrates into the entry form by adding a button to change password. However, the original button that opened the password generator doesn't work anymore. The problem is fixed once I remove this plugin.

OS: Windows 10
KeePass Version: 2.56
Plugin Version: 2.16.1

**Comment by Rookiestyle** [comment]
It still works for me.
What exactly does not work for you?

The original button opens a context menu which you can use to chose an existing profile or to open the password generator.
Does the context menu open?
Do the context menu entries for other profiles work?


Which other plugins do you have installed?

**Comment by lavinger** [comment]
Thanks for a quick reply. The issue might be in other plugins indeed.

The context menu doesn't open for the original button (as shown in your second picture). However, I can open the password generator through the change password assistant and then everything works for me.

My other plugins are:
KeeOtp2
KeePassCPEO
KeeTheme
LockAssist
Readable Passphrase Plugin

They are all up-to-date.

**Comment by lavinger** [comment]
I think it's the KeeTheme plugin that's breaking it.

**Comment by lavinger** [comment]
Thank you very much for your work. :) @Rookiestyle
