### ISSUE TITLE
Add compatibility with KeePassCPEO plugin

### ISSUE THREAD

**Issue by lavinger** [Rookiestyle/PasswordChangeAssistant#26]
In the dialog that is added by this plugin for changing password, the DateBox for setting the password expiration does not include custom options added by other plugin KeePassCPEO. I would expect that the DateBox will display the same options as in the default/original entry dialog.

OS: Win 10
KeePass Version: 2.56
Plugin Version: 2.16.2

Thank you for your time.

**Comment by Rookiestyle** [comment]
I do not plan adding that out of two reasons.

1. I would need to copy more or less the complete KeePassCPOE plugin as it is hard coded to use the entry form and nothing else
2. I developed a similar plugin named PEDCalc which integrates nicely ;) And it will also extend password expiry time upon change of password.
