### ISSUE TITLE
Entry-specific auto-type sequence selection

### ISSUE THREAD

**Issue by caspadan** [Rookiestyle/PasswordChangeAssistant#28]
## Overview
If you have an entry that has a PCA entry-specific auto-type sequence, and in PCA you select one of the other options from the Password Change Sequence dropdown, then when choosing "entry-specific sequence" again, the sequence does not change.

## Steps to Reproduce
As above.
I must say I have not checked if there is conflict from another plugin, but it seems unlikely.

## Expected Behavior
The password change sequence should change to the sequence you select in all cases.

## Actual Behavior
Does not select change to the entry-specific sequence again after selecting another sequence - have to close PCA window and open it again for the entry specific sequence to be correctly selected.

## Context
[NOTE]: # (Provide any additional information you may have)
OS: Win10x64
KeePass Version: 2.57
Plugin Version: 2.17

**Comment by Rookiestyle** [comment]
The next release will show an already saved entry-specific sequence if "Entry-specific" is selected. 
It will not show a new entry-specific sequence that you might have started typing
