### ISSUE TITLE
Password-pattern never in config file

### ISSUE THREAD

**Issue by jkr-wrk** [Rookiestyle/PasswordChangeAssistant#5]
I don't know if it already works this way but I never want to be able to see my password pattern in my config file.

Not my last used, not my default. I want to store my Patterns in the keepass database.

The Keepass generator is a nice tool. But if my pattern is capletter-digid-letter-digid this is much stronger when the pattern is unknown then if the pattern is leaked. (62)^4=1e7 or 26^2*10^2=6e4

Is this something you support?

**Comment by Rookiestyle** [comment]
You can decide where you want the profiles to stored and you can decide this by pasword profile.
By default, password profiles are stored in the config file. 
This is KeePass' standard behaviour and PasswordChangeAssistant won't change that standard.

If you want a new profile to be stored in the database, tick the *Save db-specific* in the *Save as Profile* window for that.
If you want to move a profile from config file to database/from database to config, you have to use PasswordChangeAssistant's options. See the [wiki](https://github.com/Rookiestyle/PasswordChangeAssistant/wiki/Synchronize-password-profiles) for more details.


As an additional note: 
Saving the profiles in the database is more a convenience feature than a security feature.
If a password generator profile defines weak passwords then the security risk is a weak password, not the profile. See [Kerckhoffs's principle](https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle).
