### ISSUE TITLE
GUI conflict with new password quality estimator button in KeePass 2.48

### ISSUE THREAD

**Issue by leftdisconnected** [Rookiestyle/PasswordChangeAssistant#7]
## Summary
This is not a bug in Password Change Assistant, but a new GUI conflict with KeePass 2.48 due to overlapping buttons in Edit Entry windows.

## Detail
The KDBX4.1 database format now allows the password quality estimator to be enabled and disabled for each entry.  The toggle button for this feature is now located in the same place as the Password Change Assistant button for each entry.

This is not a problem for people that don't care about enabling or disabling the quality estimation and I have observed no instability or display issues, but it will probably cause problems and confusion for many users unless the matter is documented and accepted as a fair tradeoff or dealt with in some other manner.

[NOTE]: Users can still enable/disable password quality estimation on _New_ entries as PCA does not display its button on new entries.  The native button is no longer visible on existing entries.

## Idea
I do not see an obvious place to relocate the PCA button, which is unfortunate, but it might be acceptable to replace the button with a line item under the "Generate a password" dropdown button menu that says "Change Password..." or something similar underneath the native "Open Password Generator..." option.

Unfortunately, this approach might sacrifice the shortcut options for "Old Password: Copy", etc. that exist under the current button.  Including these directly under the "Generate a password" button may consume an unreasonable amount of space as there are presently 5 lines under the PCA button.  

Though I'm not fond of nested submenus, it might be practical to have a single "Change password..." entry under the password button that opened an on-hover submenu containing the current PCA dropdown items.  [Link to an image demonstration](https://photos.google.com/share/AF1QipOYuMJNMJCCR_oT6kEaNAofRq-vGamo977UZWcRzhXk44aFx8Xlr_RgvvAlDRePmw/photo/AF1QipOw96i8KlcpXtpMg_apzHYS0CHegHwLb1JMFWRS?key=WkE3VlpwQ2VmSnlGXzhsT1AtbjRiV0JBeUR1bjVB) for clarity.

Thanks for reading and for all of your great plugins.

**Comment by Rookiestyle** [comment]
This is already fixed with [v2.11](https://github.com/Rookiestyle/PasswordChangeAssistant/releases/tag/v2.11)

**Comment by leftdisconnected** [comment]
How embarrassing.  I'm very sorry to have missed this before posting :(.  I just returned to remove it and apologize for wasting your time.
