### ISSUE TITLE
README.md shows release date incorrectly

### ISSUE THREAD

**Issue by mi-hol** [Rookiestyle/PasswordChangeAssistant#8]
## Overview
"release date" is incorrectly displayed as "may"
![image](https://user-images.githubusercontent.com/22799428/127500482-ae1d5806-7091-4c85-ba92-0c39d6a55420.png)
could be caused by an issue in shields.io

**Comment by Rookiestyle** [comment]
Version 2.11 was released on May 8th.
I don't see anything wrong here.

What would you expect to see?

**Comment by mi-hol** [comment]
I'd expect a full date but when I tested it on shields.io only month gets displayed.
Moving the issue to shields.io

**Comment by mi-hol** [comment]
https://github.com/badges/shields/issues/3218
